name: Container job sample 
on:
  push:

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: ruby:3.1.2
    steps:
      - name: show ruby version
        run: ruby -v
      - name: show uname
        run: uname -a