name: workflow at PR Merged

on:
  pull_request:
    types:
      - closed

jobs:
  merged:
    if: github.event.pull_request.merged == true
    name: PR Merged
    runs-on: ubuntu-latest
    steps:
      - name: show context
        run: |
          echo ${{ toJSON(github.event.pull_request) }}
