name: workflow at PR Merged

on:
  pull_request:
    types:
      - closed
    # branches:
    #   - 'release/**'

jobs:
  merged:
    if: github.event.pull_request.merged == true
    name: PR Merged
    runs-on: ubuntu-latest
    steps:
      - name: show context
        run: |
          echo ${{ github.event.pull_request }}
