name: Main

on:
  push:
    tags:
      - "test-*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            README.md
            assets/*.yml
            assets/00_japan*